site_name: Kedro Light
theme:
  features:
    - content.code.copy
  name: material
  palette:
    primary: orange
    scheme: slate
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 
nav:
  - index.md
  - usage.md
plugins: []
repo_url: https://github.com/ellwise/kedro-light
