name: Docs

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v3
      - run: git config user.name github-actions[bot]
      - run: git config user.email github-actions[bot]@users.noreply.github.com
      - run: make docs-deploy
